[package]
name = "zax_workspace_service"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"

[dependencies]
tonic = "0.12"
prost = "0.13"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }

[build-dependencies]
tonic-build = "0.12"

[lints]
workspace = true
